version: '3'

services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=map
    volumes:
      - $PWD/docker/mongo-data:/data/db
    ports:
      - 127.0.0.1:27017:27017
